query cycleChunkInDateRange($cycleId: String!, $input: InDateRangeInput!) {
  cycleChunkInDateRange(cycleId: $cycleId, inDateRangeInput: $input) {
    id
    compareWithPrevious
    ...ChunkDateRange
  }
}
